---
- name: Prepare
  hosts: all
  tasks:
    - name: install python for SELinux and cryptography for ca role
      package:
        name:
          - policycoreutils-python-utils
          - python3-cryptography
          - iproute
