#---
#
#- name: Verify
#  hosts: all
#  tasks:
#
#    - name: Verify redis status
#      command: "redis-cli -h {{ ansible_dns.nameservers }} -p {{ redis_configurations[0]['redis_port'] }} -a changeme info stats"
