---
# The workaround for arbitrarily named role directory is important because the
# git repo has one name and the role within it another
# Found at:
# https://github.com/ansible-community/molecule/issues/1567#issuecomment-436876722
- name: Converge
  hosts: all
  vars:
    redis_kernel_virtual_memory: 1
    redis_transparent_hugepages_value: 'madvise'
  tasks:
    - name: "Include redis_cluster role"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
