---

- name: Enable redis module
  command: "dnf -y module enable redis:{{ redis_version }}"
  changed_when: false
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "8" 

- name: Install redis
  package: 
    name: redis
