---

- name: Verify
  hosts: all
  tasks:
    - name: Verify redis status
      command: "redis-cli -h {{ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0])}} -p {% if redis_configurations [0]['redis_port'] %} -a {{ redis_requirepass }} info stats"
