---

- name: Verify
  hosts: all
  tasks:
    - name: setup
      setup:

    - name: Verify redis status
      command: "redis-cli -h {{ansible_default_ipv4.address}} -p {{ redis_configurations [0]['redis_port'] }} -a {{ redis_requirepass }} info stats"
