---

- name: Verify
  hosts: all
  tasks:
    - name: setup
      setup:
      register: result

    - name: Prit result
      debug:
        var: result

    #- name: Verify redis status
    #  command: "redis-cli -h {{ ansible_dns.nameservers }} -p {{ redis_configurations[0]['redis_port'] }} -a changeme info stats"
